//movies
export const GET_MOVIE_NOWPLAYING_LIST = "GET_MOVIE_LIST";
export const IS_LOADING_MOVIE_NOWPLAYING_LIST =
  "IS_LOADING_MOVIE_NOWPLAYING_LISTS";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const IS_LOADING_DETAIL = "IS_LOADING_DETAIL";
