//movies
export const GET_MOVIE_POPULAR_LIST = "GET_MOVIE_POPULAR_LIST";
export const IS_LOADING_MOVIE_POPULAR_LIST = "IS_LOADING_MOVIE_POPULAR_LISTS";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const IS_LOADING_DETAIL = "IS_LOADING_DETAIL";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
